nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
codigo_seccion = input("Ingrese su Código-sección: ")
sede = input("Ingrese su sede: ")

print("\nInformación recopilada:")
print(f"Nombre: {nombre}")
print(f"Apellido: {apellido}")
print(f"Código-sección: {codigo_seccion}")
print(f"Sede: {sede}")